server:
  port: ${SERVER_PORT:8080}

spring:
  data:
    redis:
      host: ${PROD_REDIS_URL:piku-valkey.xxxxxx.ng.0001.apn2.cache.amazonaws.com}
      port: 6379
      username: ${PROD_REDIS_USERNAME:piku-app-user}
      password: ${PROD_REDIS_PASSWORD:1234}
  datasource:
    url: ${PROD_DB_URL:jdbc:mysql://localhost:3306/piku} # 개발용 DB URL (필요시 _dev 추가)
    username: ${PROD_DB_USERNAME:root}
    password: ${PROD_DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

discord:
  webhook:
    url: "${DISCORD_WEBHOOK_URL:discord_webhook_url}"
