server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${PROD_DB_URL:jdbc:mysql://localhost:3306/piku} # 개발용 DB URL (필요시 _dev 추가)
    username: ${PROD_DB_USERNAME:root}
    password: ${PROD_DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

discord:
  webhook:
    url: "${DISCORD_WEBHOOK_URL:discord_webhook_url}"

storage:
  endpoint: https://s3.ap-northeast-2.amazonaws.com
  region: ap-northeast-2
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  bucket: piku-prod-bucket