spring:
  application:
    name: piku-back
  profiles:
    active: ${PROFILE:dev}
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 7MB
      max-request-size: 7MB
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
    redis:
      host: localhost
      port: 6379
  jpa:
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL:piku@gmail.com}
    password: ${EMAIL_PWD:abcd abcd efgh efgh}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

gemini:
  api:
    key: ${GEMINI_API_KEY:api-key-placeholder}
    base-url: https://generativelanguage.googleapis.com/v1beta
    models:
      image-generation: gemini-2.0-flash-preview-image-generation
      chat: gemini-2.0-flash
    timeout: 30s

jwt:
  secret: ${JWT_KEY:LhVYSkvR90p9A7jPFlWWZ0uB3RPiIGnN8s3aXk2lbE4=}

management:
  endpoints:
    web:
      exposure:
        include: health

storage:
  endpoint: ${STORAGE_URL:http://localhost:9000}
  region: ap-northeast-2
  access-key: ${STORAGE_ACCESS_KEY:minioadmin}
  secret-key: ${STORAGE_SECRET_KEY:minioadmin}
  bucket: ${STORAGE_BUCKET:piku}