package com.pikume.back.admin.domain;

public enum AdminSessionPhase {
	ANONYMOUS,
	ONBOARDING_SET_LOGIN_ID,
	ONBOARDING_SET_PASSWORD,
	ONBOARDING_REGISTER_OTP,
	ONBOARDING_VERIFY_OTP,
	LOGIN_VERIFY_OTP,
	AUTHENTICATED
}
