package com.pikume.back.admin.application.exception;

public enum AdminErrorCode {
	UNAUTHENTICATED,
	FORBIDDEN,
	CSRF_INVALID,
	NOT_FOUND,
	INVALID_CREDENTIALS,
	TEMPORARY_CREDENTIAL_EXPIRED,
	ACCOUNT_LOCKED,
	DUPLICATE_EMAIL,
	DUPLICATE_LOGIN_ID,
	INVALID_REQUEST,
	OTP_VERIFICATION_FAILED,
	OTP_BLOCKED,
	SESSION_STORE_UNAVAILABLE
}
